### PR TITLE
Fix @BsonDiscriminator codec registration

### LINKED ISSUE #10: @BsonDiscriminator not fully working
Although it's not documented in Micronaut Mongo, a feature of the mongo driver is that you can map elements of a collection to specific subclasses based on a field called the discriminator, see this example in C# https://stackoverflow.com/questions/18465529/mongodb-mapping-an-interface-to-an-implementation
Or the docs for this feature in the C# driver https://mongodb.github.io/mongo-csharp-driver/2.8/reference/bson/mapping/polymorphism/

My issue is that I could not find a mechanism to register classes with the automatic Pojo codec, so the code is flaky. For some reason at insert time the inserted class is registered automatically, so my current workaround for this is to insert and delete one item of every type I'm dealing with. The mapping of discriminator key to Class is in org.bson.codecs.pojo.DiscriminatorLookup

See this example: https://github.com/mnembrini/micronaut-bug-bson-discriminator

In there there is an Animal base class with subclasses Dog and Cat, and a single mongoDB collection "animal". The expectation is that we get the right class when reading based on the discriminator key "type"

In AnimalRepositoryTest, if you run the whole test class, everything passes, because there is an insert of both Dog and Cat classes in the DB.
If after that you run only the test readCatWithoutInsertingFirst(), it will fail with the following exception

```
An exception occurred when decoding using the AutomaticPojoCodec.
Decoding into a 'Animal' failed with the following exception:

Failed to decode 'Animal'. Decoding errored with: A class could not be found for the discriminator: 'some_cat_type'.

A custom Codec or PojoCodec may need to be explicitly configured and registered to handle this type.
org.bson.codecs.configuration.CodecConfigurationException: An exception occurred when decoding using the AutomaticPojoCodec.
Decoding into a 'Animal' failed with the following exception:

Failed to decode 'Animal'. Decoding errored with: A class could not be found for the discriminator: 'some_cat_type'.

A custom Codec or PojoCodec may need to be explicitly configured and registered to handle this type.
	at org.bson.codecs.pojo.AutomaticPojoCodec.decode(AutomaticPojoCodec.java:40)
	at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51)
	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:409)
	at com.mongodb.internal.connection.InternalStreamConnection.access$900(InternalStreamConnection.java:74)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:394)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:372)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:667)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:634)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:510)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:507)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:562)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:137)
	at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:105)
	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:507)
	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:74)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:624)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:609)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:510)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:507)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: org.bson.codecs.configuration.CodecConfigurationException: Failed to decode 'Animal'. Decoding errored with: A class could not be found for the discriminator: 'some_cat_type'.
	at org.bson.codecs.pojo.PojoCodecImpl.getCodecFromDocument(PojoCodecImpl.java:354)
	at org.bson.codecs.pojo.PojoCodecImpl.decode(PojoCodecImpl.java:124)
	at org.bson.codecs.pojo.AutomaticPojoCodec.decode(AutomaticPojoCodec.java:37)
	... 41 more
Caused by: org.bson.codecs.configuration.CodecConfigurationException: A class could not be found for the discriminator: 'some_cat_type'.
	at org.bson.codecs.pojo.DiscriminatorLookup.lookup(DiscriminatorLookup.java:51)
	at org.bson.codecs.pojo.PojoCodecImpl.getCodecFromDocument(PojoCodecImpl.java:352)
	... 43 more
```

The test readDogWithoutInsertingFirst instead works, because the discriminator key for Dog is the name of the class. This is also another possible workaround, but I don't think it's robust

### PR DESCRIPTION
**Pull request by graemerocher**
## Summary
- register introspected `@BsonDiscriminator` types with the Pojo codec provider before package registration
- keep discovery limited to Micronaut bean introspections in configured packages
- add a focused regression test for discriminator-based subtype decoding without priming the subtype codec

Resolves #10

### CODE REVIEW

**Comment by graemerocher** [comment]
@copilot apply changes based on the comments in [this thread](https://github.com/micronaut-projects/micronaut-mongodb/pull/880#pullrequestreview-4121153103)

File: mongo-core/src/main/java/io/micronaut/configuration/mongo/core/DefaultCodecRegistryBuilder.java [hunk 1]
```diff
@@ -84,14 +90,47 @@ public CodecRegistry build(AbstractMongoConfiguration configuration) {
...
         return fromRegistries(codecRegistries);
     }
+
+    private Collection<Class<?>> findDiscriminatorEntities(Collection<String> packageNames) {
+        List<String> packageNamesKey = normalizePackageNamesForCaching(packageNames);
+        Collection<Class<?>> cachedEntities = discriminatorEntitiesCache.get(packageNamesKey);
+        if (cachedEntities != null) {
+            return cachedEntities;
+        }
+        Collection<Class<?>> discoveredEntities = List.copyOf(BeanIntrospector.SHARED.findIntrospectedTypes(reference ->
```
Comment (radovanradic) [inline mongo-core/src/main/java/io/micronaut/configuration/mongo/core/DefaultCodecRegistryBuilder.java:112]: So this will work only for `@Introspected` classes? Does it resolve original issue and does it need maybe add to the documentation?

Comment (graemerocher) [reply mongo-core/src/main/java/io/micronaut/configuration/mongo/core/DefaultCodecRegistryBuilder.java:112]: documentation is a good idea, I believe it does, the issue was locating the classes that need to be registered

**Review by radovanradic — APPROVED** [review]
